### ISSUE TITLE
HTTP Error: 401 Client Error

### ISSUE THREAD

**Issue by rubikstriangle** [BinaryAlley/DatasetTag#3]
My install seemed to go fine but when I'm in the GUI and try to caption an image I get this error:
HTTP Error: 401 Client Error: Unauthorized for url: https://api.openai.com/v1/chat/completions

Any ideas why?

**Comment by rubikstriangle** [comment]
Looks like I got ahead of my self,  I want back to the install instructions and found the bit about the API key.  Trying that now...

**Comment by rubikstriangle** [comment]
Looks like I got a bit ahead of myself, I wen't back to the instructions and found the bit about the API key.

**Comment by rubikstriangle** [comment]
I obtained an api key from https://platform.openai.com/api-keys and pasted it into the first box "API Key" in the GUI but it still doesn't work. Is this the correct location to obtain an API key?
Still getting:
HTTP Error: 404 Client Error: Not Found for url: https://api.openai.com/v1/chat/completions

**Comment by BinaryAlley** [comment]
Wrong repository, this one contains no code related to OpenAI or any other platform.
