### ISSUE TITLE
[Request] The user should be able to train without a trigger word for style training

### ISSUE THREAD

**Issue by Jellybit** [BinaryAlley/DatasetTag#4]
For styles, it's generally better not to use a trigger word (or specify photo/painting), as you want it to assume that everything should look like it does in your style, every time. Same goes for certain elements in a concept, like if it should always show the full body, you don't want to tag "full body", because you don't want to give the lora a choice in doing that. Currently, when you try to simply type a description, it won't let you save it because you're missing a trigger word.

Part of this should also ensure that any regular tags or miscellaneous tags don't have a space and comma at the beginning of the prompt. It should just start with whatever tag you put in there, miscellaneous or regular.

Thanks for considering this! It would make the tool useful for more training approaches, and I don't think it would take anything away from those who use it as currently designed.

EDIT: I made the change, and it seems to be working okay? I guess I should make a branch? I've never done this before.

**Comment by Jellybit** [comment]
With that request post done, I want to say that this is a great tool, and is one I've been looking for for a good while! It's so easy to use, and I can get through images so quickly. I really can't imagine not using this, except that it doesn't like people putting in only the tags they want. Thank you very much for making this tool!

**Comment by BinaryAlley** [comment]
Thanks for reporting, it was indeed not something I thought about, as I created it for trainings that did require a trigger word. 

I'm sorry for not reading more carefully your post, I did not observe that you already made a fix - I would have encouraged you to commit it, especially if it was your first... Maybe next time :)

As for the procedure, it's a bit more complicated - when you are not the project maintainer and you do not have access to make changes to the repository (such as creating new branches), you need to fork it first - this creates your personal copy of the entire repository. It is this copy that you can then clone locally, modify in any way (add new branches or not, add commits, etc), and push back to the forked repository. Then, you would make a pull or merge request in the original repository, with relevant info, such as description of changes, reference to the issue it fixes, etc. Finally, the request is reviewed by the project owner or contributors, and they can possibly request changes. Once approved, it is merged in the main codebase, and it becomes part of the project.

Regardless, I am very glad to hear that you find this program useful, it does help me a lot too. Enjoy!
