### ISSUE TITLE
Executable?

### ISSUE THREAD

**Issue by Humanoidme** [BinaryAlley/DatasetTag#6]
Hi I am able to start the application from command line but I don't find the DatasetTag.exe in any folder? Where is it supposed to be ? Thanks

**Comment by BinaryAlley** [comment]
Depends what you mean by "start the application from command line". If you mean "compile it from source", you need to download the entire source code, navigate to the folder where the .csproj file is located, and use the "dotnet run" command. That will build the project (produce the executable) and also run it. The executable should also be placed in the "bin" folder, at the same directory level as the "src" one.

If you meant "run it from command line like a console application", you can only launch it from the console, not pass arguments or parameters to it, like you would to a console application.

However, I think that the easiest way for you would be to just download the already compiled executable binaries, of which there is a Windows version too (.exe). You can find them on the [releases page](https://github.com/BinaryAlley/DatasetTag/releases) of this repository, particularily the DatasetTag-v1.0.2.0-windows-x64.tar.gz file, which is an archive you can extract with WinRAR or 7Zip (i think - don't quote me on it - but the idea remains, its just an archive). Inside it, you will find a folder containing the executable file.

I'm going to close this, if you have further questions or need assistance, feel free to re-open.
