### ISSUE TITLE
Copy paste tags from image to image

### ISSUE THREAD

**Issue by Alphascosl** [BinaryAlley/DatasetTag#7]
Hey, I just found this helpful tool and i am more than pleased with how it works. Finally a tagger with categories that I can use as a checklist 👍 

Only thing which would be an awesome enhancement:
The ability to copy the tags from a selected image and then select another image and paste the copied tags. This would speed up tagging with similar images a lot.

Also a small quality of life change would be to adjust the background colors to a more neutral dark grey. Doesn't need to be a fully dark mode, but tagging 1000+ images with these bright colors in the background (the buttons are totally fine) will give me eyestrain 😄 

Otherwise keep up the good work!

**Comment by BinaryAlley** [comment]
Thanks!
Copy/paste feature was implemented in 2cd7505. I will create a new release after implementing the theme feature too.

**Comment by BinaryAlley** [comment]
Basic theming is also implemented, you can get the latest version from the [releases page](https://github.com/BinaryAlley/DatasetTag/releases).
